[package]
name = "rimuy/gamejoy"
description = "Simple class-based input library"
version = "2.0.0"
license = "MIT"
authors = ["Rimuy"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["*"]
include = [
        "include",
        "include/**/*",
        "out",
        "out/**/*",
        "LICENSE",
        "README.md",
        "default.project.json",
        "node_modules",
        "node_modules/@rbxts",
        "node_modules/@rbxts/**/*",
        "wally.toml",
]

[dependencies]